/// Date helpers that keep plan scheduling anchored to local calendar days.
library;

/// Rounds [dt] to the nearest local midnight.
///
/// Plan days are calendar days, but historic schedules were generated by
/// adding 24-hour [Duration]s, which drifts to 01:00 (spring forward) or to
/// 23:00 of the previous day (fall back) across a daylight-saving transition.
/// Rounding to the *nearest* midnight repairs both directions, and is a no-op
/// for dates that are already at midnight.
DateTime normalizeToLocalMidnight(DateTime dt) {
  final floor = DateTime(dt.year, dt.month, dt.day);
  final ceil = DateTime(dt.year, dt.month, dt.day + 1);
  return dt.difference(floor) <= ceil.difference(dt) ? floor : ceil;
}
