import 'package:bible_tracker/core/models/bible_book.dart';

// All 73 Catholic Bible books in SSV canonical order.
// ssvSlug values verified against biblia.ssv.sk.
// chapterCount values verified against the live SSV website for books
// that differ from Protestant canon (Esther=16, Daniel=14, Joel=4, Tobit=14, Baruch=6).
const List<BibleBook> kBibleBooks = [
  // ── OLD TESTAMENT ────────────────────────────────────────────────────────

  // Pentateuch
  BibleBook(
    id: 'gen',
    name: 'Genezis',
    shortName: 'Gn',
    order: 1,
    testament: Testament.oldTestament,
    category: CatholicCategory.pentateuch,
    chapterCount: 50,
    isDeuterocanonical: false,
    ssvSlug: 'genezis-prva-kniha-mojzisova',
  ),
  BibleBook(
    id: 'exod',
    name: 'Exodus',
    shortName: 'Ex',
    order: 2,
    testament: Testament.oldTestament,
    category: CatholicCategory.pentateuch,
    chapterCount: 40,
    isDeuterocanonical: false,
    ssvSlug: 'exodus-druha-kniha-mojzisova',
  ),
  BibleBook(
    id: 'lev',
    name: 'Levitikus',
    shortName: 'Lv',
    order: 3,
    testament: Testament.oldTestament,
    category: CatholicCategory.pentateuch,
    chapterCount: 27,
    isDeuterocanonical: false,
    ssvSlug: 'levitikus-tretia-kniha-mojzisova',
  ),
  BibleBook(
    id: 'num',
    name: 'Numeri',
    shortName: 'Nm',
    order: 4,
    testament: Testament.oldTestament,
    category: CatholicCategory.pentateuch,
    chapterCount: 36,
    isDeuterocanonical: false,
    ssvSlug: 'kniha-numeri-stvrta-kniha-mojzisova',
  ),
  BibleBook(
    id: 'deut',
    name: 'Deuteronómium',
    shortName: 'Dt',
    order: 5,
    testament: Testament.oldTestament,
    category: CatholicCategory.pentateuch,
    chapterCount: 34,
    isDeuterocanonical: false,
    ssvSlug: 'kniha-deuteronomium-piata-kniha-mojzisova',
  ),

  // Historical Books
  BibleBook(
    id: 'josh',
    name: 'Jozue',
    shortName: 'Joz',
    order: 6,
    testament: Testament.oldTestament,
    category: CatholicCategory.historicalBooks,
    chapterCount: 24,
    isDeuterocanonical: false,
    ssvSlug: 'kniha-jozue',
  ),
  BibleBook(
    id: 'judg',
    name: 'Sudcovia',
    shortName: 'Sdc',
    order: 7,
    testament: Testament.oldTestament,
    category: CatholicCategory.historicalBooks,
    chapterCount: 21,
    isDeuterocanonical: false,
    ssvSlug: 'kniha-sudcov',
  ),
  BibleBook(
    id: 'ruth',
    name: 'Rút',
    shortName: 'Rút',
    order: 8,
    testament: Testament.oldTestament,
    category: CatholicCategory.historicalBooks,
    chapterCount: 4,
    isDeuterocanonical: false,
    ssvSlug: 'kniha-rut',
  ),
  BibleBook(
    id: '1sam',
    name: 'Prvá kniha Samuelova',
    shortName: '1Sam',
    order: 9,
    testament: Testament.oldTestament,
    category: CatholicCategory.historicalBooks,
    chapterCount: 31,
    isDeuterocanonical: false,
    ssvSlug: 'prva-kniha-samuelova',
  ),
  BibleBook(
    id: '2sam',
    name: 'Druhá kniha Samuelova',
    shortName: '2Sam',
    order: 10,
    testament: Testament.oldTestament,
    category: CatholicCategory.historicalBooks,
    chapterCount: 24,
    isDeuterocanonical: false,
    ssvSlug: 'druha-kniha-samuelova',
  ),
  BibleBook(
    id: '1kgs',
    name: 'Prvá kniha kráľov',
    shortName: '1Kr',
    order: 11,
    testament: Testament.oldTestament,
    category: CatholicCategory.historicalBooks,
    chapterCount: 22,
    isDeuterocanonical: false,
    ssvSlug: 'prva-kniha-kralov',
  ),
  BibleBook(
    id: '2kgs',
    name: 'Druhá kniha kráľov',
    shortName: '2Kr',
    order: 12,
    testament: Testament.oldTestament,
    category: CatholicCategory.historicalBooks,
    chapterCount: 25,
    isDeuterocanonical: false,
    ssvSlug: 'druha-kniha-kralov',
  ),
  BibleBook(
    id: '1chr',
    name: 'Prvá kniha kroník',
    shortName: '1Krn',
    order: 13,
    testament: Testament.oldTestament,
    category: CatholicCategory.historicalBooks,
    chapterCount: 29,
    isDeuterocanonical: false,
    ssvSlug: 'prva-kniha-kronik',
  ),
  BibleBook(
    id: '2chr',
    name: 'Druhá kniha kroník',
    shortName: '2Krn',
    order: 14,
    testament: Testament.oldTestament,
    category: CatholicCategory.historicalBooks,
    chapterCount: 36,
    isDeuterocanonical: false,
    ssvSlug: 'druha-kniha-kronik',
  ),
  BibleBook(
    id: 'ezra',
    name: 'Ezdráš',
    shortName: 'Ezd',
    order: 15,
    testament: Testament.oldTestament,
    category: CatholicCategory.historicalBooks,
    chapterCount: 10,
    isDeuterocanonical: false,
    ssvSlug: 'kniha-ezdrasova',
  ),
  BibleBook(
    id: 'neh',
    name: 'Nehemiáš',
    shortName: 'Neh',
    order: 16,
    testament: Testament.oldTestament,
    category: CatholicCategory.historicalBooks,
    chapterCount: 13,
    isDeuterocanonical: false,
    ssvSlug: 'kniha-nehemiasova',
  ),
  BibleBook(
    id: 'tob',
    name: 'Tobiáš',
    shortName: 'Tob',
    order: 17,
    testament: Testament.oldTestament,
    category: CatholicCategory.historicalBooks,
    chapterCount: 14,
    isDeuterocanonical: true,
    ssvSlug: 'kniha-tobias',
  ),
  BibleBook(
    id: 'jdt',
    name: 'Judita',
    shortName: 'Jdt',
    order: 18,
    testament: Testament.oldTestament,
    category: CatholicCategory.historicalBooks,
    chapterCount: 16,
    isDeuterocanonical: true,
    ssvSlug: 'kniha-judita',
  ),
  // Esther: 16 chapters in Catholic canon (includes deuterocanonical additions);
  // isDeuterocanonical=false because the book itself is protocanonical.
  BibleBook(
    id: 'esth',
    name: 'Ester',
    shortName: 'Est',
    order: 19,
    testament: Testament.oldTestament,
    category: CatholicCategory.historicalBooks,
    chapterCount: 16,
    isDeuterocanonical: false,
    ssvSlug: 'kniha-ester',
  ),

  // Wisdom Books
  BibleBook(
    id: 'job',
    name: 'Jób',
    shortName: 'Jób',
    order: 20,
    testament: Testament.oldTestament,
    category: CatholicCategory.wisdomBooks,
    chapterCount: 42,
    isDeuterocanonical: false,
    ssvSlug: 'kniha-job',
  ),
  BibleBook(
    id: 'ps',
    name: 'Žalmy',
    shortName: 'Ž',
    order: 21,
    testament: Testament.oldTestament,
    category: CatholicCategory.wisdomBooks,
    chapterCount: 150,
    isDeuterocanonical: false,
    ssvSlug: 'kniha-zalmov',
  ),
  BibleBook(
    id: 'prov',
    name: 'Príslovia',
    shortName: 'Prís',
    order: 22,
    testament: Testament.oldTestament,
    category: CatholicCategory.wisdomBooks,
    chapterCount: 31,
    isDeuterocanonical: false,
    ssvSlug: 'kniha-prislovi',
  ),
  BibleBook(
    id: 'eccl',
    name: 'Kazateľ',
    shortName: 'Kaz',
    order: 23,
    testament: Testament.oldTestament,
    category: CatholicCategory.wisdomBooks,
    chapterCount: 12,
    isDeuterocanonical: false,
    ssvSlug: 'kniha-kazatel',
  ),
  BibleBook(
    id: 'song',
    name: 'Pieseň piesní',
    shortName: 'Pies',
    order: 24,
    testament: Testament.oldTestament,
    category: CatholicCategory.wisdomBooks,
    chapterCount: 8,
    isDeuterocanonical: false,
    ssvSlug: 'piesen-piesni',
  ),
  BibleBook(
    id: 'wis',
    name: 'Múdrosť',
    shortName: 'Múd',
    order: 25,
    testament: Testament.oldTestament,
    category: CatholicCategory.wisdomBooks,
    chapterCount: 19,
    isDeuterocanonical: true,
    ssvSlug: 'kniha-mudrosti',
  ),
  BibleBook(
    id: 'sir',
    name: 'Sirachovec',
    shortName: 'Sir',
    order: 26,
    testament: Testament.oldTestament,
    category: CatholicCategory.wisdomBooks,
    chapterCount: 51,
    isDeuterocanonical: true,
    ssvSlug: 'kniha-sirachovcova',
  ),

  // Prophetic Books
  BibleBook(
    id: 'isa',
    name: 'Izaiáš',
    shortName: 'Iz',
    order: 27,
    testament: Testament.oldTestament,
    category: CatholicCategory.propheticBooks,
    chapterCount: 66,
    isDeuterocanonical: false,
    ssvSlug: 'kniha-proroka-izaiasa',
  ),
  BibleBook(
    id: 'jer',
    name: 'Jeremiáš',
    shortName: 'Jer',
    order: 28,
    testament: Testament.oldTestament,
    category: CatholicCategory.propheticBooks,
    chapterCount: 52,
    isDeuterocanonical: false,
    ssvSlug: 'kniha-proroka-jeremiasa',
  ),
  BibleBook(
    id: 'lam',
    name: 'Náreky',
    shortName: 'Nár',
    order: 29,
    testament: Testament.oldTestament,
    category: CatholicCategory.propheticBooks,
    chapterCount: 5,
    isDeuterocanonical: false,
    ssvSlug: 'kniha-nareky',
  ),
  BibleBook(
    id: 'bar',
    name: 'Baruch',
    shortName: 'Bar',
    order: 30,
    testament: Testament.oldTestament,
    category: CatholicCategory.propheticBooks,
    chapterCount: 6,
    isDeuterocanonical: true,
    ssvSlug: 'kniha-proroka-barucha',
  ),
  BibleBook(
    id: 'ezek',
    name: 'Ezechiel',
    shortName: 'Ez',
    order: 31,
    testament: Testament.oldTestament,
    category: CatholicCategory.propheticBooks,
    chapterCount: 48,
    isDeuterocanonical: false,
    ssvSlug: 'kniha-proroka-ezechiela',
  ),
  // Daniel: 14 chapters in Catholic canon (includes Azariah, Susanna, Bel & Dragon).
  // isDeuterocanonical=false because the book is protocanonical; only additions differ.
  BibleBook(
    id: 'dan',
    name: 'Daniel',
    shortName: 'Dan',
    order: 32,
    testament: Testament.oldTestament,
    category: CatholicCategory.propheticBooks,
    chapterCount: 14,
    isDeuterocanonical: false,
    ssvSlug: 'kniha-proroka-daniela',
  ),
  BibleBook(
    id: 'hos',
    name: 'Ozeáš',
    shortName: 'Oz',
    order: 33,
    testament: Testament.oldTestament,
    category: CatholicCategory.propheticBooks,
    chapterCount: 14,
    isDeuterocanonical: false,
    ssvSlug: 'kniha-proroka-ozeasa',
  ),
  // Joel: 4 chapters in Catholic/Vulgate tradition (Protestant canon has 3).
  BibleBook(
    id: 'joel',
    name: 'Joel',
    shortName: 'Joel',
    order: 34,
    testament: Testament.oldTestament,
    category: CatholicCategory.propheticBooks,
    chapterCount: 4,
    isDeuterocanonical: false,
    ssvSlug: 'kniha-proroka-joela',
  ),
  BibleBook(
    id: 'amos',
    name: 'Ámos',
    shortName: 'Am',
    order: 35,
    testament: Testament.oldTestament,
    category: CatholicCategory.propheticBooks,
    chapterCount: 9,
    isDeuterocanonical: false,
    ssvSlug: 'kniha-proroka-amosa',
  ),
  BibleBook(
    id: 'obad',
    name: 'Abdiáš',
    shortName: 'Abd',
    order: 36,
    testament: Testament.oldTestament,
    category: CatholicCategory.propheticBooks,
    chapterCount: 1,
    isDeuterocanonical: false,
    ssvSlug: 'kniha-proroka-abdiasa',
  ),
  BibleBook(
    id: 'jon',
    name: 'Jonáš',
    shortName: 'Jon',
    order: 37,
    testament: Testament.oldTestament,
    category: CatholicCategory.propheticBooks,
    chapterCount: 4,
    isDeuterocanonical: false,
    ssvSlug: 'kniha-proroka-jonasa',
  ),
  BibleBook(
    id: 'mic',
    name: 'Micheáš',
    shortName: 'Mich',
    order: 38,
    testament: Testament.oldTestament,
    category: CatholicCategory.propheticBooks,
    chapterCount: 7,
    isDeuterocanonical: false,
    ssvSlug: 'kniha-proroka-micheasa',
  ),
  BibleBook(
    id: 'nah',
    name: 'Nahum',
    shortName: 'Nah',
    order: 39,
    testament: Testament.oldTestament,
    category: CatholicCategory.propheticBooks,
    chapterCount: 3,
    isDeuterocanonical: false,
    ssvSlug: 'kniha-proroka-nahuma',
  ),
  BibleBook(
    id: 'hab',
    name: 'Habakuk',
    shortName: 'Hab',
    order: 40,
    testament: Testament.oldTestament,
    category: CatholicCategory.propheticBooks,
    chapterCount: 3,
    isDeuterocanonical: false,
    ssvSlug: 'kniha-proroka-habakuka',
  ),
  BibleBook(
    id: 'zeph',
    name: 'Sofoniáš',
    shortName: 'Sof',
    order: 41,
    testament: Testament.oldTestament,
    category: CatholicCategory.propheticBooks,
    chapterCount: 3,
    isDeuterocanonical: false,
    ssvSlug: 'kniha-proroka-sofoniasa',
  ),
  BibleBook(
    id: 'hag',
    name: 'Aggeus',
    shortName: 'Ag',
    order: 42,
    testament: Testament.oldTestament,
    category: CatholicCategory.propheticBooks,
    chapterCount: 2,
    isDeuterocanonical: false,
    ssvSlug: 'kniha-proroka-aggea',
  ),
  BibleBook(
    id: 'zech',
    name: 'Zachariáš',
    shortName: 'Zach',
    order: 43,
    testament: Testament.oldTestament,
    category: CatholicCategory.propheticBooks,
    chapterCount: 14,
    isDeuterocanonical: false,
    ssvSlug: 'kniha-proroka-zachariasa',
  ),
  BibleBook(
    id: 'mal',
    name: 'Malachiáš',
    shortName: 'Mal',
    order: 44,
    testament: Testament.oldTestament,
    category: CatholicCategory.propheticBooks,
    chapterCount: 3,
    isDeuterocanonical: false,
    ssvSlug: 'kniha-proroka-malachiasa',
  ),

  // Maccabees — Historical Books, placed at end of OT per SSV canonical ordering
  BibleBook(
    id: '1macc',
    name: 'Prvá kniha Machabejcov',
    shortName: '1Mach',
    order: 45,
    testament: Testament.oldTestament,
    category: CatholicCategory.historicalBooks,
    chapterCount: 16,
    isDeuterocanonical: true,
    ssvSlug: 'prva-kniha-machabejcov',
  ),
  BibleBook(
    id: '2macc',
    name: 'Druhá kniha Machabejcov',
    shortName: '2Mach',
    order: 46,
    testament: Testament.oldTestament,
    category: CatholicCategory.historicalBooks,
    chapterCount: 15,
    isDeuterocanonical: true,
    ssvSlug: 'druha-kniha-machabejcov',
  ),

  // ── NEW TESTAMENT ────────────────────────────────────────────────────────

  // Gospels
  BibleBook(
    id: 'matt',
    name: 'Evanjelium podľa Matúša',
    shortName: 'Mt',
    order: 47,
    testament: Testament.newTestament,
    category: CatholicCategory.gospels,
    chapterCount: 28,
    isDeuterocanonical: false,
    ssvSlug: 'evanjelium-podla-matusa',
  ),
  BibleBook(
    id: 'mark',
    name: 'Evanjelium podľa Marka',
    shortName: 'Mk',
    order: 48,
    testament: Testament.newTestament,
    category: CatholicCategory.gospels,
    chapterCount: 16,
    isDeuterocanonical: false,
    ssvSlug: 'evanjelium-podla-marka',
  ),
  BibleBook(
    id: 'luke',
    name: 'Evanjelium podľa Lukáša',
    shortName: 'Lk',
    order: 49,
    testament: Testament.newTestament,
    category: CatholicCategory.gospels,
    chapterCount: 24,
    isDeuterocanonical: false,
    ssvSlug: 'evanjelium-podla-lukasa',
  ),
  BibleBook(
    id: 'john',
    name: 'Evanjelium podľa Jána',
    shortName: 'Jn',
    order: 50,
    testament: Testament.newTestament,
    category: CatholicCategory.gospels,
    chapterCount: 21,
    isDeuterocanonical: false,
    ssvSlug: 'evanjelium-podla-jana',
  ),

  // Acts
  BibleBook(
    id: 'acts',
    name: 'Skutky apoštolov',
    shortName: 'Sk',
    order: 51,
    testament: Testament.newTestament,
    category: CatholicCategory.acts,
    chapterCount: 28,
    isDeuterocanonical: false,
    ssvSlug: 'skutky-apostolov',
  ),

  // Pauline Letters (14 letters including Hebrews per Catholic tradition)
  BibleBook(
    id: 'rom',
    name: 'List Rimanom',
    shortName: 'Rim',
    order: 52,
    testament: Testament.newTestament,
    category: CatholicCategory.paulineLetters,
    chapterCount: 16,
    isDeuterocanonical: false,
    ssvSlug: 'list-rimanom',
  ),
  BibleBook(
    id: '1cor',
    name: 'Prvý list Korinťanom',
    shortName: '1Kor',
    order: 53,
    testament: Testament.newTestament,
    category: CatholicCategory.paulineLetters,
    chapterCount: 16,
    isDeuterocanonical: false,
    ssvSlug: 'prvy-list-korintanom',
  ),
  BibleBook(
    id: '2cor',
    name: 'Druhý list Korinťanom',
    shortName: '2Kor',
    order: 54,
    testament: Testament.newTestament,
    category: CatholicCategory.paulineLetters,
    chapterCount: 13,
    isDeuterocanonical: false,
    ssvSlug: 'druhy-list-korintanom',
  ),
  BibleBook(
    id: 'gal',
    name: 'List Galaťanom',
    shortName: 'Gal',
    order: 55,
    testament: Testament.newTestament,
    category: CatholicCategory.paulineLetters,
    chapterCount: 6,
    isDeuterocanonical: false,
    ssvSlug: 'list-galatanom',
  ),
  BibleBook(
    id: 'eph',
    name: 'List Efezanom',
    shortName: 'Ef',
    order: 56,
    testament: Testament.newTestament,
    category: CatholicCategory.paulineLetters,
    chapterCount: 6,
    isDeuterocanonical: false,
    ssvSlug: 'list-efezanom',
  ),
  BibleBook(
    id: 'phil',
    name: 'List Filipanom',
    shortName: 'Flp',
    order: 57,
    testament: Testament.newTestament,
    category: CatholicCategory.paulineLetters,
    chapterCount: 4,
    isDeuterocanonical: false,
    ssvSlug: 'list-filipanom',
  ),
  BibleBook(
    id: 'col',
    name: 'List Kolosanom',
    shortName: 'Kol',
    order: 58,
    testament: Testament.newTestament,
    category: CatholicCategory.paulineLetters,
    chapterCount: 4,
    isDeuterocanonical: false,
    ssvSlug: 'list-kolosanom',
  ),
  BibleBook(
    id: '1thess',
    name: 'Prvý list Solúnčanom',
    shortName: '1Sol',
    order: 59,
    testament: Testament.newTestament,
    category: CatholicCategory.paulineLetters,
    chapterCount: 5,
    isDeuterocanonical: false,
    ssvSlug: 'prvy-list-soluncanom',
  ),
  BibleBook(
    id: '2thess',
    name: 'Druhý list Solúnčanom',
    shortName: '2Sol',
    order: 60,
    testament: Testament.newTestament,
    category: CatholicCategory.paulineLetters,
    chapterCount: 3,
    isDeuterocanonical: false,
    ssvSlug: 'druhy-list-soluncanom',
  ),
  BibleBook(
    id: '1tim',
    name: 'Prvý list Timotejovi',
    shortName: '1Tim',
    order: 61,
    testament: Testament.newTestament,
    category: CatholicCategory.paulineLetters,
    chapterCount: 6,
    isDeuterocanonical: false,
    ssvSlug: 'prvy-list-timotejovi',
  ),
  BibleBook(
    id: '2tim',
    name: 'Druhý list Timotejovi',
    shortName: '2Tim',
    order: 62,
    testament: Testament.newTestament,
    category: CatholicCategory.paulineLetters,
    chapterCount: 4,
    isDeuterocanonical: false,
    ssvSlug: 'druhy-list-timotejovi',
  ),
  BibleBook(
    id: 'tit',
    name: 'List Títovi',
    shortName: 'Tít',
    order: 63,
    testament: Testament.newTestament,
    category: CatholicCategory.paulineLetters,
    chapterCount: 3,
    isDeuterocanonical: false,
    ssvSlug: 'list-titovi',
  ),
  BibleBook(
    id: 'phlm',
    name: 'List Filemonovi',
    shortName: 'Flm',
    order: 64,
    testament: Testament.newTestament,
    category: CatholicCategory.paulineLetters,
    chapterCount: 1,
    isDeuterocanonical: false,
    ssvSlug: 'list-filemonovi',
  ),
  BibleBook(
    id: 'heb',
    name: 'List Hebrejom',
    shortName: 'Hebr',
    order: 65,
    testament: Testament.newTestament,
    category: CatholicCategory.paulineLetters,
    chapterCount: 13,
    isDeuterocanonical: false,
    ssvSlug: 'list-hebrejom',
  ),

  // Catholic Letters
  BibleBook(
    id: 'jas',
    name: 'Jakubov list',
    shortName: 'Jak',
    order: 66,
    testament: Testament.newTestament,
    category: CatholicCategory.catholicLetters,
    chapterCount: 5,
    isDeuterocanonical: false,
    ssvSlug: 'jakubov-list',
  ),
  BibleBook(
    id: '1pet',
    name: 'Prvý Petrov list',
    shortName: '1Pt',
    order: 67,
    testament: Testament.newTestament,
    category: CatholicCategory.catholicLetters,
    chapterCount: 5,
    isDeuterocanonical: false,
    ssvSlug: 'prvy-petrov-list',
  ),
  BibleBook(
    id: '2pet',
    name: 'Druhý Petrov list',
    shortName: '2Pt',
    order: 68,
    testament: Testament.newTestament,
    category: CatholicCategory.catholicLetters,
    chapterCount: 3,
    isDeuterocanonical: false,
    ssvSlug: 'druhy-petrov-list',
  ),
  BibleBook(
    id: '1john',
    name: 'Prvý Jánov list',
    shortName: '1Jn',
    order: 69,
    testament: Testament.newTestament,
    category: CatholicCategory.catholicLetters,
    chapterCount: 5,
    isDeuterocanonical: false,
    ssvSlug: 'prvy-janov-list',
  ),
  BibleBook(
    id: '2john',
    name: 'Druhý Jánov list',
    shortName: '2Jn',
    order: 70,
    testament: Testament.newTestament,
    category: CatholicCategory.catholicLetters,
    chapterCount: 1,
    isDeuterocanonical: false,
    ssvSlug: 'druhy-janov-list',
  ),
  BibleBook(
    id: '3john',
    name: 'Tretí Jánov list',
    shortName: '3Jn',
    order: 71,
    testament: Testament.newTestament,
    category: CatholicCategory.catholicLetters,
    chapterCount: 1,
    isDeuterocanonical: false,
    ssvSlug: 'treti-janov-list',
  ),
  BibleBook(
    id: 'jude',
    name: 'Júdov list',
    shortName: 'Júd',
    order: 72,
    testament: Testament.newTestament,
    category: CatholicCategory.catholicLetters,
    chapterCount: 1,
    isDeuterocanonical: false,
    ssvSlug: 'judov-list',
  ),

  // Revelation
  BibleBook(
    id: 'rev',
    name: 'Zjavenie apoštola Jána',
    shortName: 'Zjv',
    order: 73,
    testament: Testament.newTestament,
    category: CatholicCategory.revelation,
    chapterCount: 22,
    isDeuterocanonical: false,
    ssvSlug: 'zjavenie-apostola-jana-apokalypsa',
  ),
];
